"use client";
import { use, useEffect, useState } from "react";
import Image from "next/image";
import styles from "./page.module.css";
import Head from "next/head";
import Pagination from "./pagination";
import { paginate } from "./paginate";

export default function Home() {
  const [currentPage, setCurrentPage] = useState(1);
  const [data, setData] = useState([]);
  const [List, setList] = useState([]);

  const pageSize = 10;
  const onPageChange = (page) => {
    setCurrentPage(page);
  };
  const getStaticProps = async () => {
    const res = await fetch("https://jsonplaceholder.typicode.com/todos");
    const data = await res.json();
    setData(data);
  };
  useEffect(() => {
    getStaticProps();
  }, []);
  useEffect(() => {
    const paginatedPosts = paginate(data, currentPage, pageSize);
    setList(paginatedPosts);
  }, [currentPage, pageSize, data]);
  return (
    <div className={styles?.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p className={styles?.title}>
        <strong>NextJS x Pagination</strong>
      </p>
      {List?.map((item) => {
        console.log("item", item);
        return (
          <p key={item.id} className={styles?.list}>
            {item.title}
          </p>
        );
      })}
      <Pagination
        items={data?.length} // 100
        currentPage={currentPage} // 1
        pageSize={pageSize} // 10
        onPageChange={onPageChange}
      />
    </div>
  );
}
